print('======Desafio 02 ======')
dia = input('Qual é a data do seu aniversário? ')
mes = input('Qual é o mês seu aniversário? ')
ano = input('Qual é o ano do seu aniversário? ')
print('Você nasceu no dia', dia,'de',mes,'de',ano,'.Correto?')
